config/routes.rb
Rails.application.routes.draw do

  namespace :users_backoffice do
    get "welcome/index"
    resources :fato
      match 'fato/:departamento_id/:status_id/(:mesano)/index' => 'fato#index', via: 'get'
      match 'fato/:id/concluir_tarefa' => 'fato#concluir_tarefa', via: 'get'
      match 'fato/:id/desfazer_conclusao' => 'fato#desfazer_conclusao', via: 'get'
    resources :log_usuario
      match 'log_usuario/:tarefa_id/historico' => 'log_usuario#historico', via: 'get'
  end

  namespace :admins_backoffice do
    get "welcome/index"
  end

  devise_for :users

  devise_for :admins
  
  get "home/index"
  
  resources :empresa
  match "delete_empresa" => "empresa#delete_empresa", via: "get"
  match "empresa/:id/edit" => "empresa#update", via: "post"
  match "admins_backoffice/empresa/criar_tarefas_mensais" => "admins_backoffice/empresa#criar_tarefas_mensais", via: "post"
  match "empresa/criar_tarefas_mensais" => "empresa#criar_tarefas_mensais", via: "post"
  
  resources :departamento
  match "delete_departamento" => "departamento#delete_departamento", via: "get"
  match "departamento/:id/edit" => "departamento#update", via: "post"

  resources :colaborador
  match "delete_colaborador" => "colaborador#delete_colaborador", via: "get"
  match "colaborador/:id/edit" => "colaborador#update", via: "post"

  resources :tarefa
  match "delete_tarefa" => "tarefa#delete_tarefa", via: "get"
  match "tarefa/:id/edit" => "tarefa#update", via: "post"
  
  root to: "home#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/colaborador.rb
class Colaborador < ApplicationRecord
    belongs_to :departamento
    belongs_to :user
end

app/models/departamento.rb
class Departamento < ApplicationRecord
    has_many :colaboradors
    has_many :tarefas
    has_many :fatos
    belongs_to :situacao
end

app/models/empresa.rb
class Empresa < ApplicationRecord
    has_many :fatos
    belongs_to :situacao
end

app/models/fato.rb
class Fato < ApplicationRecord
    belongs_to :tarefa
    belongs_to :empresa
    belongs_to :departamento
    belongs_to :status
end

app/models/log_usuario.rb
class LogUsuario < ApplicationRecord
end

app/models/situacao.rb
class Situacao < ApplicationRecord
    has_many :departamentos
    has_many :tarefas
    has_many :empresas
end

app/models/status.rb
class Status < ApplicationRecord
    has_many :fatos
end

app/models/tarefa.rb
class Tarefa < ApplicationRecord
    belongs_to :departamento
    belongs_to :situacao
    has_many :fatos
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

    def menu_lateral
        conn = ActiveRecord::Base.connection
        @departamento = conn.execute "SELECT id, nomeDepartamento, abreviacao FROM departamentos ORDER BY nomeDepartamento ASC;"
    end

    def mes_atual
        conn = ActiveRecord::Base.connection
        @mes_atual = conn.select_one "SELECT MAX(REPLACE(RIGHT(date_format(str_to_date(dataVencimentoTarefa, '%Y-%m-%d'), '%d/%m/%Y'),7),'/','')) AS mes_atual FROM fatos;"
    end

    def teste
        conn = ActiveRecord::Base.connection
        @empresas = conn.execute "SELECT id FROM empresas WHERE statusEmpresa = 'Ativa';"
        @tarefas =  conn.execute "SELECT t.id AS id_tarefa, d.id AS id_departamento FROM departamentos AS d JOIN tarefas AS t ON t.departamento_id = d.id;"

        @empresa_tarefa

        @empresas.each do |e|
            @tarefas.each do |t|
                @empresa_tarefa = conn.execute "INSERT INTO fatos (dataVencimentoTarefa, tarefa_id, empresa_id, departamento_id, status_id) VALUES ('2019/09/12', #{d[0]}, #{e[0]}, #{d[1]}, 2);" 
            end
        end
    end

end

app/helpers/colaborador_helper.rb
module ColaboradorHelper
end

app/helpers/empresa_helper.rb
module EmpresaHelper
end

app/helpers/fato_helper.rb
module FatoHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/situacao_helper.rb
module SituacaoHelper
end

app/helpers/status_helper.rb
module StatusHelper
end

app/helpers/tarefa_helper.rb
module TarefaHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<!DOCTYPE html>

<html>

<head>

    <meta charset="UTF-8">
    <link rel = "stylesheet" type="text/css" href="index.css">
    <title>Home</title>

</head>

<body>

    <div id="container-cabecalho">
        
        <div id="logo">
            <%= image_tag("AVG Branco", height: 80, width: 140)%> 
        </div>
        
        <div id="login-cabecalho">
            <a href="">Home</a>
            <a href="">Sobre nós</a>
            <a href="">Contato</a>
            <%= link_to 'Área do colaborador', users_backoffice_welcome_index_path%>
            <%= link_to 'Área do gestor', admins_backoffice_welcome_index_path%>
        </div>
    </div>

    <div class="area-parallax">

        <div class="titulo-parallax">
            Acessível, <br>
            Prático, <br>
            Moderno
        </div>

        <div class="imagem-parallax">
            <%= image_tag("AVG Colorido", height: 320, width: 560)%>
        </div>

    </div>

    <div class="conteudo">
        <h1>30 ANOS DE TRADIÇÃO</h1>
        <p>Nosso serviço veio com a ideia de trazer mais controle das rotinas de seu escritório trazendo
        um resumo de situações de todas as tarefas, com agilidade e simplicidade, visando
        maior rendimento de todos os colaboradores.</p>
    </div>

    <div id="rodape">
        Todos os direitos reservados, 2019.
    </div>
    
</body>

</html>