config/routes.rb
Rails.application.routes.draw do

  namespace :users_backoffice do
    get "welcome/index"
    resources :fato
      match 'fato/:departamento_id/:status_id/(:mesano)/index' => 'fato#index', via: 'get'
      match 'fato/:id/concluir_tarefa' => 'fato#concluir_tarefa', via: 'get'
      match 'fato/:id/desfazer_conclusao' => 'fato#desfazer_conclusao', via: 'get'
    resources :log_usuario
      match 'log_usuario/:tarefa_id/historico' => 'log_usuario#historico', via: 'get'
  end

  namespace :admins_backoffice do
    get "welcome/index"
  end

  devise_for :users

  devise_for :admins
  
  get "home/index"
  
  resources :empresa
  match "delete_empresa" => "empresa#delete_empresa", via: "get"
  match "empresa/:id/edit" => "empresa#update", via: "post"
  match "admins_backoffice/empresa/criar_tarefas_mensais" => "admins_backoffice/empresa#criar_tarefas_mensais", via: "post"
  match "empresa/criar_tarefas_mensais" => "empresa#criar_tarefas_mensais", via: "post"
  
  resources :departamento
  match "delete_departamento" => "departamento#delete_departamento", via: "get"
  match "departamento/:id/edit" => "departamento#update", via: "post"

  resources :colaborador
  match "delete_colaborador" => "colaborador#delete_colaborador", via: "get"
  match "colaborador/:id/edit" => "colaborador#update", via: "post"

  resources :tarefa
  match "delete_tarefa" => "tarefa#delete_tarefa", via: "get"
  match "tarefa/:id/edit" => "tarefa#update", via: "post"
  
  root to: "home#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/colaborador.rb
class Colaborador < ApplicationRecord
    belongs_to :departamento
    belongs_to :user
end

app/models/departamento.rb
class Departamento < ApplicationRecord
    has_many :colaboradors
    has_many :tarefas
    has_many :fatos
    belongs_to :situacao
end

app/models/empresa.rb
class Empresa < ApplicationRecord
    has_many :fatos
    belongs_to :situacao
end

app/models/fato.rb
class Fato < ApplicationRecord
    belongs_to :tarefa
    belongs_to :empresa
    belongs_to :departamento
    belongs_to :status
end

app/models/log_usuario.rb
class LogUsuario < ApplicationRecord
end

app/models/situacao.rb
class Situacao < ApplicationRecord
    has_many :departamentos
    has_many :tarefas
    has_many :empresas
end

app/models/status.rb
class Status < ApplicationRecord
    has_many :fatos
end

app/models/tarefa.rb
class Tarefa < ApplicationRecord
    belongs_to :departamento
    belongs_to :situacao
    has_many :fatos
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

    def menu_lateral
        conn = ActiveRecord::Base.connection
        @departamento = conn.execute "SELECT id, nomeDepartamento, abreviacao FROM departamentos ORDER BY nomeDepartamento ASC;"
    end

    def mes_atual
        conn = ActiveRecord::Base.connection
        @mes_atual = conn.select_one "SELECT MAX(REPLACE(RIGHT(date_format(str_to_date(dataVencimentoTarefa, '%Y-%m-%d'), '%d/%m/%Y'),7),'/','')) AS mes_atual FROM fatos;"
    end

    def teste
        conn = ActiveRecord::Base.connection
        @empresas = conn.execute "SELECT id FROM empresas WHERE statusEmpresa = 'Ativa';"
        @tarefas =  conn.execute "SELECT t.id AS id_tarefa, d.id AS id_departamento FROM departamentos AS d JOIN tarefas AS t ON t.departamento_id = d.id;"

        @empresa_tarefa

        @empresas.each do |e|
            @tarefas.each do |t|
                @empresa_tarefa = conn.execute "INSERT INTO fatos (dataVencimentoTarefa, tarefa_id, empresa_id, departamento_id, status_id) VALUES ('2019/09/12', #{d[0]}, #{e[0]}, #{d[1]}, 2);" 
            end
        end
    end

end

app/helpers/empresa_helper.rb
module EmpresaHelper
end

app/helpers/fato_helper.rb
module FatoHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/situacao_helper.rb
module SituacaoHelper
end

app/helpers/status_helper.rb
module StatusHelper
end

app/helpers/tarefa_helper.rb
module TarefaHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Entrar", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <% link_to "Criar Conta", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Esqueceu a senha?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Não recebeu instruções de confirmação?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Não recebeu instruções de desbloqueio?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Faça login com #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ForBusiness</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag params[:controller] %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    
    <%= javascript_include_tag params[:controller] %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/users_backoffice.html.erb
<!DOCTYPE html>
<html>
  <head>
  
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Usuário | ForBusiness</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %> 

    <%= stylesheet_link_tag    'users_backoffice' %>
    <!-- Custom fonts for this template-->

    <style type="text/css">/* Chart.js */
    </style>
  </head>

  <body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

      <!-- Sidebar -->
      <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

        <!-- Sidebar - Brand -->
        
          <div id="logo">
            <%= image_tag("AVG Branco", height: 60, width: 100)%> 
          </div>
        

        <!-- Divider -->
        <hr class="sidebar-divider my-0">

        <!-- Nav Item - Dashboard -->
        <li class="nav-item active">
          <%= link_to users_backoffice_welcome_index_path, class:"nav-link" do %>
              <i class="fa fa-dashboards"></i>
              <span>Dashboard</span>
            <% end %>
        </li>

        <!-- Divider -->
        <hr class="sidebar-divider">

        <!-- Heading -->
        <div class="sidebar-heading">
            Departamentos
        </div>

          <!-- Area com separação de departamentos e tarefas  -->
        <% menu_lateral.each do |d| %>
          <li class="nav-item active">
            <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#<%= d[2] %>" aria-expanded="true">
              <i class="fa fa-users"></i>
              <span> <%= d[1] %> </span>
            </a>
            <div id="<%= d[2] %>" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
              <div class="bg-white py-2 collapse-inner rounded">
                <h6 class="collapse-header">Status:</h6>
                <%= link_to "Tarefas pendentes", {controller: "fato", action: "index", departamento_id: d[0], status_id: 2, mesano: mes_atual['mes_atual'] }, class: "collapse-item" %> 
                <%= link_to "Tarefas concluídas", {controller: "fato", action: "index", departamento_id: d[0], status_id: 1, mesano: mes_atual['mes_atual']}, class: "collapse-item" %>
              </div>
            </div>
          </li>
        <% end %>
          
        <!-- Divider -->
        <hr class="sidebar-divider d-none d-md-block">

        <!-- Sidebar Toggler (Sidebar) -->
        <div class="text-center d-none d-md-inline">
          <button class="rounded-circle border-0" id="sidebarToggle"></button>
        </div>

      </ul>
      <!-- End of Sidebar -->

      <!-- Content Wrapper -->
      <div id="content-wrapper" class="d-flex flex-column">

        <!-- Main Content -->
        <div id="content">

          <!-- Topbar -->
          <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

            <!-- Sidebar Toggle (Topbar) -->
            <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
              <i class="fa fa-bars"></i>
            </button>


            <!-- Topbar Search -->
            <form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
              <div class="input-group">
                
              </div>
            </form>

            <!-- Topbar Navbar -->
            <ul class="navbar-nav ml-auto">

              <!-- Nav Item - Search Dropdown (Visible Only XS) -->
              <li class="nav-item dropdown no-arrow d-sm-none">
                <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <i class="fas fa-search fa-fw"></i>
                </a>
                <!-- Dropdown - Messages -->
                <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in" aria-labelledby="searchDropdown">
                  <form class="form-inline mr-auto w-100 navbar-search">
                    <div class="input-group">
                      <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
                      <div class="input-group-append">
                        <button class="btn btn-primary" type="button">
                          <i class="fas fa-search fa-sm"></i>
                        </button>
                      </div>
                    </div>
                  </form>
                </div>
              </li>

              <!-- Nav Item - Alerts -->
              <li class="nav-item dropdown no-arrow mx-1">
                <a class="nav-link dropdown-toggle" href="#" id="alertsDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  
                  <!-- Counter - Alerts -->
                  
                </a>
                <!-- Dropdown - Alerts -->
              
              </li>

              <!-- Nav Item - Messages -->
              <li class="nav-item dropdown no-arrow mx-1">
                <a class="nav-link dropdown-toggle" href="#" id="messagesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  
                  <!-- Counter - Messages -->
                  
                </a>
                <!-- Dropdown - Messages -->
                <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="messagesDropdown">
                  </div>
              </li>

              <div class="topbar-divider d-none d-sm-block"></div>

              <!-- Nav Item - User Information -->
              <li class="nav-item dropdown no-arrow">
                  <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                    <span class="mr-2 d-none d-lg-inline text-gray-600 small"><%= current_user.email %></span>
                      <%= image_tag 'user.png', class:"img-profile rounded-circle" %>
                  </a>
                <!-- Dropdown - User Information -->
                <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
                  <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                    <i class="fa fa-sign fa-fw"></i>
                    Sair
                  </a>
                </div>
              </li>

            </ul>

          </nav>
          <!-- End of Topbar -->

          <!-- Begin Page Content -->
          <div class="container-fluid">

            <!-- Page Heading -->
            
            <%= yield %>

          </div>
          <!-- /.container-fluid -->

        </div>
        <!-- End of Main Content -->

        <!-- Footer -->
        <footer class="sticky-footer bg-white">
          <div class="container my-auto">
            <div class="copyright text-center my-auto">
              <span>Copyright &copy; AVG Devs 2019</span>
            </div>
          </div>
        </footer>
        <!-- End of Footer -->

      </div>
      <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->

    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
      <i class="fa fa-angle-up"></i>
    </a>

    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Pronto para partir?</h5>
            <button class="close" type="button" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">×</span>
            </button>
          </div>
          <div class="modal-body">Selecione "Sair" abaixo se você estiver pronto para terminar sua sessão atual.</div>
          <div class="modal-footer">
            <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancelar</button>
              <%= link_to "Sair", destroy_user_session_path, method: :delete, class:"btn btn-primary" %>
          </div>
        </div>
      </div>
    </div>
    
    <%= javascript_include_tag 'users_backoffice' %>

  </body>
</html>